version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    ports:
      - "8000:8000"
    command: ./entrypoint.sh
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: /bin/bash -c "npm install && npm run dev"
    networks:
      - my_network

volumes:
  db-data:
    driver: local

networks:
  my_network:
    driver: bridge
