version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend/db:/app/db
    ports:
      - "8000:8000"
    command: /bin/bash -c "pip install -r /app/requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - my_network
    environment:
      - PYTHONPATH=/app
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: /bin/bash -c "npm install && npm run dev"
    networks:
      - my_network

volumes:
  db-data:
    driver: local

networks:
  my_network:
    driver: bridge
